version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: findpeople-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: findpeople

  backend:
    build: ../backend
    container_name: findpeople-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/findpeople
      - JWT_SECRET=your-production-jwt-secret
      - PORT=3000
    volumes:
      - ../backend:/app
      - /app/node_modules

  frontend:
    build: ../frontend
    container_name: findpeople-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: